### ISSUE TITLE
VallueError: Found input variables with inconsistent numbers of samples

### ISSUE THREAD

**Issue by iwillflyandfly** [amazon-research/patchcore-inspection#22]
When I try to  evaluating a pretrained PatchCore model like cable, it raises ValueError :" Found input variables with inconsistent numbers of samples: [15360000, 7526400]"
INFO:__main__:Evaluating dataset [mvtec_cable] (1/1)...
INFO:patchcore.patchcore:Loading and initializing PatchCore.
INFO:__main__:Embedding test data with models (1/1)
INFO:__main__:Computing evaluation metrics.
Traceback (most recent call last):
  File "src/load_and_evaluate_patchcore.py", line 286, in <module>
    main()
  File "/home/lihang/anaconda3/envs/lihang-conda/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/lihang/anaconda3/envs/lihang-conda/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/lihang/anaconda3/envs/lihang-conda/lib/python3.8/site-packages/click/core.py", line 1689, in invoke
    return _process_result(rv)
  File "/home/lihang/anaconda3/envs/lihang-conda/lib/python3.8/site-packages/click/core.py", line 1626, in _process_result
    value = ctx.invoke(self._result_callback, value, **ctx.params)
  File "/home/lihang/anaconda3/envs/lihang-conda/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "src/load_and_evaluate_patchcore.py", line 154, in run
    pixel_scores = patchcore.metrics.compute_pixelwise_retrieval_metrics(
  File "/home/lihang/patchcore/patchcore-inspection/src/patchcore/metrics.py", line 47, in compute_pixelwise_retrieval_metrics
    fpr, tpr, thresholds = metrics.roc_curve(
  File "/home/lihang/anaconda3/envs/lihang-conda/lib/python3.8/site-packages/sklearn/metrics/_ranking.py", line 979, in roc_curve
    fps, tps, thresholds = _binary_clf_curve(
  File "/home/lihang/anaconda3/envs/lihang-conda/lib/python3.8/site-packages/sklearn/metrics/_ranking.py", line 740, in _binary_clf_curve
    check_consistent_length(y_true, y_score, sample_weight)
  File "/home/lihang/anaconda3/envs/lihang-conda/lib/python3.8/site-packages/sklearn/utils/validation.py", line 387, in check_consistent_length
    raise ValueError(
ValueError: Found input variables with inconsistent numbers of samples: [15360000, 7526400]

**Comment by iwillflyandfly** [comment]
Many thanks!

**Comment by TheWangYang** [comment]
#### I finally solved the problem and the analysis is as follows:
* When training my model input parameters are set as follows: --resize 256 --imagesize 244;
* But when I loaded the pre-trained model, I set the model input parameters as follows: --resize 366 --imagesize 320;
* The reason is that when training and evaluating the same model, the image input sizes are not consistent;
* Finally, modify the input parameters of the evaluation model to those input during model training;
